eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: queryService
          uri: http://localhost:8090
          predicates:
            - Path=/substances/**
        - id : commandService
          uri : http://localhost:8070
          predicates:
            - Path=/substances/**
