eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8090
spring:
  application:
    name: queryService
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: hydatis
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      name: substances